// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Common;
using System;
using System.Collections.Generic;

namespace Entities.Models;

public class AcademyClaseMaster : Entity
{ 

    public Guid? AcademyDataId { get; set; }

    public Guid? BranchesDataId { get; set; }

    public Guid? GovernorateCodeId { get; set; }

    public Guid? CityCodeId { get; set; }

    public string ClaseNameL1 { get; set; }

    public string ClaseNameL2 { get; set; }

    public string ClaseAddress { get; set; }

    public string Location { get; set; }

    public string ClaseOwnerName { get; set; }

    public string OwnerMobil { get; set; }

    public string CommunicationsOfficer { get; set; }

    public string CommunicationsMobil { get; set; }

    public string EmailClase { get; set; }

    public string EmailOwner { get; set; }

    public int? ClaseBranchNo { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<AcademyClaseDetail> AcademyClaseDetails { get; set; } = new List<AcademyClaseDetail>();

    public virtual BranchData BranchesData { get; set; }

    public virtual CityCode CityCode { get; set; }

    public virtual GovernorateCode GovernorateCode { get; set; }
}