// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Entities.Models;

public class AcademyClaseType : Entity
{ 
    [MaxLength(100)]
    public string ClassTypeNameId { get; set; }

}