// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Entities.Models.System;

namespace Entities.Models;

public class CityCode : Entity
{
     

    public Guid? GovernorateCodeId { get; set; }

    [MaxLength(100)]
    public string CityNameL1 { get; set; }

    [MaxLength(100)]
    public string CityNameL2 { get; set; }

   
    public virtual ICollection<AcademyClaseMaster> AcademyClaseMasters { get; set; } = new List<AcademyClaseMaster>();

    public virtual ICollection<BranchData> BranchesData { get; set; } = new List<BranchData>();

    public virtual GovernorateCode GovernorateCode { get; set; }

    public virtual ICollection<StudentData> StudentData { get; set; } = new List<StudentData>();

    public virtual ICollection<TeacherData> TeacherData { get; set; } = new List<TeacherData>();
}