// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public class ComplaintsStudent
{

    public Guid? AcademyDataId { get; set; }

    public Guid? BranchesDataId { get; set; }

    public int ComplaintsNo { get; set; }

    public Guid? ComplaintsTypeId { get; set; }

    public Guid? ComplaintsStatusesId { get; set; }

    public Guid? StudentsDataId { get; set; }

    public DateOnly? Date { get; set; }

    public string Description { get; set; }

    public string FilesAttch { get; set; }

    public virtual BrancheData BranchesData { get; set; }

    public virtual ComplaintsStatus ComplaintsStatuses { get; set; }

    public virtual ComplaintsType ComplaintsType { get; set; }

    public virtual StudentData StudentsData { get; set; }
}