// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Common;
using System;
using System.Collections.Generic;

namespace Entities.Models;

public class PermissionUser : Entity
{ 

    public string AspNetUsersId { get; set; }

    public long? ApplicationMenuId { get; set; }

    public bool? OpenForm { get; set; }

    public bool? AddForm { get; set; }

    public bool? EditForm { get; set; }

    public bool? DeleteForm { get; set; }

    public bool? ReadForm { get; set; }

    public bool? SearchForm { get; set; }

    public bool? FilterForm { get; set; }

    public bool? PrinterReport { get; set; }

    public bool? ExportFile { get; set; }

    public bool? ExportDataGrid { get; set; }

}